
pipeline{
   
   agent any
   tools{
	maven'Maven 3.6.1'
   }
   stages{
       stage(build){
	when{
            changeset "**/worker/**"
          }
           steps{
               echo 'Building worker app'
	       dir('worker'){
	       sh 'mvn compile'
               sleep 5
	       }
           }
       }
       stage(test){
       when{
            changeset "**/worker/**"
          }
           steps{
               echo 'Testing worker app'
	       dir('worker'){
	       sh 'mvn clean test'
               sleep 7
	       }
           }
       }
       stage(package){
      when{
            changeset "**/worker/**"
          }
           steps{
               echo 'Packaging worker app'
	      dir('worker'){
	       sh 'mvn package -Dskip test'
               sleep 3
	       }
           }
       }
   }
   post{
       always{
        archiveArtifacts '**/target/*.jar'
           echo 'This pipeline is completed'
       }
   }
}
