
pipeline{
   
   agent any
   tools{
	maven'Maven 3.6.1'
   }
   stages{
       stage(one){
           steps{
               echo 'Building worker app'
	       dir('worker'){
	       sh 'mvn compile'
               sleep 5
	       }
           }
       }
       stage(two){
           steps{
               echo 'Testing worker app'
	       sh 'mvn clean test'
               sleep 7
           }
       }
       stage(three){
           steps{
               echo 'Packaging worker app'
	       sh 'mvn package -Dskip Test
               sleep 3
           }
       }
   }
   post{
       always{
           echo 'This pipeline is completed'
       }
   }
}
